name: JeuxVideOPSBootStrap

on:
  push:
      branches:
        - 'main'

jobs:

  first_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Message de lancement
        run: echo "Hello Github Actions!"

      - name: liste des fichiers du repo 
        run: ls -la

      - name: Generation de la couverture du code   
        run: nyc --check-coverage --branches 100 --lines 100 --statements 100 --functions 100 npm run mocha:test
