name: JeuxVideOPSBootStrap

on:
  push:
      branches:
        - 'main'

jobs:

  first_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm 

      - name: Install
        run: npm ci && echo "Dépendances installées avec succès ! RAS ✅"

      - name: Message de lancement
        run: echo "Hello Github Actions!" &&  echo "Installation des dépendances réussie ! RAS ✅"

      - name: liste des fichiers du repo 
        run: ls -la && echo "Liste des fichiers affichée avec succès ! RAS ✅"

      - name: Generation de la couverture du code   
        run: npm run nyc:run && echo "Couverture du code générée avec succès ! RAS ✅"

      - name: Teste de fonctionnalité   
        run: npm run cypress:test && echo "Tests de fonctionnalité passés avec succès ! RAS ✅"

      - name: Linter le code 
        run: npm run eslint:check  && echo "Linting passé avec succès ! RAS ✅" 
      
      - name: Documentation de code 
        run: npm run jsdoc && echo "Documentation générée avec succès ! RAS ✅"  

      -name: Realisation des test unitaire 
       run: mocha:test && echo "Tests unitaires passés avec succès ! RAS ✅"  